# This file contains configuration flags to customize your site

# Name of your site (displayed in the header)
name: Estudio Nale

# Name of the author
author: Gustavo David Nale

# Short bio or description (displayed in the header)
description: Abogado. Servicios Jurídicos.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# alt: Abogado - Servicios Jurídicos en Santa Rosa La Pampa - Gustavo David Nale - Estudio Nale - estudionale@gmail.com - estudionale.com
avatar: https://estudionale.com/images/logo.svg

# Flags below are optional

# Includes an icon in the footer for each username you enter
footer-links:
  # dribbble:
  email: estudionale@gmail.com
  # facebook: estudionale/
  # flickr:
  # instagram: estudionale/
  # linkedin: 
  # pinterest: estudionale/
  # rss: rss
  # twitter: estudionale/
  # stackoverflow: 
  # youtube: channel/UCx1T0Mpi3-sTdOphQOSx9gw/ # channel/<your_long_string> or user/<user-name>
  # github:
  # googleplus: # anything in your profile username that comes after plus.google.com/
  # playconsole:
   #  rss: true  # remove this line if you don't want to show an RSS link at the bottom
   #  medium: yourname
   #  telegram: test
   #  telephone: +5492954529500
   #  reddit: yourname
   #  linkedin: daattali
   #  xing: yourname
   #  stackoverflow: "3943160/daattali"
   #  snapchat: deanat78
   #  instagram: deanat78
   #  spotify: yourname
   #  telephone: +14159998888
   #  steam: deanat78
   #  twitch: yourname
   #  yelp: yourname
   #  telegram: yourname
   #  calendly: yourname
   #  mastodon: instance.url/@username
   #  ORCID: your ORCID ID
   #  google-scholar: your google scholar
   #  discord: invite/invite_code or users/userid 
   #  kaggle: yourname
   #  hackerrank: yourname


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
# disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-228056227-1

# For newer "GA4" analytics, use the following instead of the "UA" entry above
google_analytics_ga4: G-RSCNHLXSG2

# Your website URL (e.g. http://amitmerchant1990.github.io or http://www.amitmerchant.com)
# Used for Sitemap.xml and your RSS feed
# url: http://estudionale.com  # originalmente es http y no https
url: https://estudionale.com
enforce_ssl: estudionale.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# baseurl: ""
baseurl: "https://estudionale.com"

# !! You don't need to change any of the configuration flags below !!

permalink: /:title/

# The release of Jekyll Now that you're using
# version: v1.2.0
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    # css_class: 'highlight'
    css_class: 'darcula'
    

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed vs :expanded


# Use the following plug-ins
plugins:
  # - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  # - jekyll-paginate

include: ['_pages']
 # paginate: 10
 # paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
